### ISSUE TITLE
Add CloudWatch alarms for relevant cluster metrics

### ISSUE THREAD

**Issue by sopel** [cityindex-attic/logsearch#103]
This partially supersedes #87 and #91, insofar these address specific subsets of the monitoring/notification domain only  - instead, this is likely going to be a growing list of metrics identified as relevant for smooth cluster operation, starting with:
- [x] EC2 status checks, see #87 
- [x] EC2 CPUUtilization, see https://github.com/cityindex/logsearch-development-flow/issues/87#issuecomment-22102211
- [x] EC2 NetworkIn, see https://github.com/cityindex/logsearch-development-flow/issues/87#issuecomment-22102211
- [x] non serviced queues, see #91
- [x] ... TBD ...
